
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 25 21:53:31 BRT 2014
//----------------------------------------------------

package br.unit.compiler.simple;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ID = 4;
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 5;
  public static final int TIMES = 3;
  public static final int EOF = 0;
}

